services:
  database:
    image: "postgres:latest"
    ports:
      - 5050:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
  minio:
    image: minio/minio
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}" 
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
      MINIO_DEFAULT_BUCKETS: "${MINIO_DEFAULT_BUCKET}"
    volumes:
      - ./miniolocal/data:/data # Mount a local directory for data persistence
    command: server /data --console-address ":9001"