services:
  database:
    image: "postgres:latest"
    ports:
      - 5050:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    volumes:
      - ./api/init/postgres:/docker-entrypoint-initdb.d
  minio:
    image: minio/minio
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}" 
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
      MINIO_DEFAULT_BUCKETS: "${MINIO_DEFAULT_BUCKET}"
    volumes:
      - ./api/init/minio/miniolocal/data:/data # Mount a local directory for data persistence
    command: server /data --console-address ":9001"
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "${MEILI_PORT}:7700"
    volumes:
      - ./api/init/meilisearch/meili_local/meili_data:/meili_data
    environment:
      MEILI_MASTER_KEY: "${MEILI_MASTER_KEY}"
    healthcheck:
      test: set -o pipefail;curl -fsS http://${MEILI_HOST}:${MEILI_PORT}/health | grep -q '{"status":"available"}'
      retries: 3
      timeout: 5s